apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database-application-postgresql
images:
- name: container-image-to-change
  newName: 13-v0.0.5
commonLabels:
  node.cluster.k8s.com/database: application-database-postgresql
  node.cluster.k8s.com/postgresql-version: "13"
resources:
- ../../base
